openapi: 3.1.1
info:
  version: "1.0"
  title: AppFirst
servers:
  - url: http://localhost:3000
components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
          example: Hello world
paths:
  /hello:
    get:
      summary: hello world
      responses:
        '200':
          description: Respuesta completa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
  /users:
    post:
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              required:
                - name
                - age
                - email
              properties:
                name:
                  type: string
                  minLength: 2
                age: 
                  type: integer
                  minimum: 18
                email: 
                  type: string
                  format: email
      responses:
        '201': 
          description: Usuario creado
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  id:
                    type: string
                  name: 
                    type: string
                  age: 
                    type: integer
                  email:
                    type: string
  /users/{id}:
    get:
      summary: Obtener un usuario por ID
      parameters:
        - in: path
          name: id
          required: true
          schema: 
            type: integer
      responses:
        '200': 
          description: Usuario Encontrado
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  id: 
                    type: integer
                  name: 
                    type: string
        '404':
          description: Usuario no Encontrado
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
    post:
      summary: Actualizar el nombre del usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - age
                - email
              properties:
                name:
                  type: string
                  minLength: 2
                email: 
                  type: string
                  format: email
                age: 
                  type: integer
                  minimum: 18
      responses:
        '200':
          description: Usuario actualizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  age: 
                    type: string
                  email:
                    type: string
        '400':
          description: Error en los datos enviados
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string